name: Test
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: ['1.18', '1.19', '1.20']
        include:
          - os: ubuntu-latest
            go: 1.18
          - os: macos-latest
            go: 1.18
          - os: macos-latest
            go: 1.19
    steps:
      - name: Check out sveltin
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true
          cache-dependency-path: go.sum

      - name: Install Go modules
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Run sveltin tests
        run: go test -cover -race -vet=off ./...
